# Generated by Django 4.0.4 on 2022-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=150)),
                ('Profcurs', models.CharField(max_length=50)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
    ]
